GET http://localhost:3333/doctors

###
GET http://localhost:3333/patient/555190003434

###
POST http://localhost:3333/patient
Content-Type: application/json

{
  "name": "Adriano dev",
  "phone": "555190003434",
  "password": "5432"
}

###
POST http://localhost:3333/patient/1/appointment
Content-Type: application/json
Authorization: {{$aadToken}}

{
  "patientId": 1,
  "agendaId": 1
}